backend:
  name: git-gateway
  repo: clover2024/blog
  branch: master



media_folder: 'source/images' 
public_folder: 'images' 

publish_mode: editorial_workflow


collections:
  - name: 'Post' 
    label: 'Post' 
    folder: 'source/_posts' 
    create: true 
    slug: '{{slug}}' 
    fields:
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Publish Date', name: 'date', widget: 'datetime'}
      - {label: 'Body', name: 'body', widget: 'markdown'}